# Generated by Django 6.0.1 on 2026-02-23 13:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customerfield_customertag_customer_anniversary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'db_table': 'leads_lossreason',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Pipeline')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'leads_pipeline',
                'ordering': ['-is_default', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Expected Value')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Expected Close Date')),
                ('assigned_to', models.UUIDField(blank=True, help_text='UUID of the assigned user', null=True, verbose_name='Assigned To')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('website', 'Website'), ('referral', 'Referral'), ('campaign', 'Campaign'), ('social', 'Social Media'), ('import', 'Import'), ('walk_in', 'Walk-in'), ('phone', 'Phone Call'), ('other', 'Other')], default='manual', max_length=20, verbose_name='Source')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=10, verbose_name='Status')),
                ('won_date', models.DateTimeField(blank=True, null=True, verbose_name='Won Date')),
                ('lost_date', models.DateTimeField(blank=True, null=True, verbose_name='Lost Date')),
                ('stage_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Stage Changed At')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customers.customer', verbose_name='Customer')),
                ('loss_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.lossreason', verbose_name='Loss Reason')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.pipeline', verbose_name='Pipeline')),
            ],
            options={
                'db_table': 'leads_lead',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('activity_type', models.CharField(choices=[('note', 'Note'), ('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('stage_change', 'Stage Change'), ('status_change', 'Status Change')], max_length=20, verbose_name='Activity Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'db_table': 'leads_leadactivity',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('auto_create_customer_on_win', models.BooleanField(default=False, help_text='Automatically create a customer record when a lead is won', verbose_name='Auto-create Customer on Win')),
                ('default_source', models.CharField(choices=[('manual', 'Manual'), ('website', 'Website'), ('referral', 'Referral'), ('campaign', 'Campaign'), ('social', 'Social Media'), ('import', 'Import'), ('walk_in', 'Walk-in'), ('phone', 'Phone Call'), ('other', 'Other')], default='manual', max_length=20, verbose_name='Default Source')),
                ('default_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.pipeline', verbose_name='Default Pipeline')),
            ],
            options={
                'db_table': 'leads_leadsettings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('probability', models.PositiveIntegerField(default=0, help_text='Win probability percentage (0-100)', verbose_name='Probability (%)')),
                ('color', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger'), ('info', 'Info')], default='primary', max_length=20, verbose_name='Color')),
                ('is_won', models.BooleanField(default=False, help_text='Leads moved here are automatically marked as won', verbose_name='Won Stage')),
                ('is_lost', models.BooleanField(default=False, help_text='Leads moved here are automatically marked as lost', verbose_name='Lost Stage')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='leads.pipeline', verbose_name='Pipeline')),
            ],
            options={
                'db_table': 'leads_pipelinestage',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.pipelinestage', verbose_name='Stage'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['hub_id', 'status'], name='leads_lead_hub_id_9b9630_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['hub_id', 'pipeline', 'stage'], name='leads_lead_hub_id_4dc0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['hub_id', 'assigned_to'], name='leads_lead_hub_id_50e136_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['hub_id', 'source'], name='leads_lead_hub_id_6239b3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['hub_id', 'priority'], name='leads_lead_hub_id_7b00e8_idx'),
        ),
    ]
